[package]
name = "satellite"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rdkafka = { version = "0.28", features = ["tokio"] }
warp = "0.3"
futures = "0.3"